// Submagic's implementation of CaptionRenderer.
//
// This is the translation boundary. Above it, everything speaks Clipiro:
// template slugs, our 13 render statuses, CaptionWord. Below it, everything
// speaks Submagic: template names, whatever status vocabulary they use, their
// word shape. Nothing leaks in either direction — that's what makes §43's
// eventual migration to a native renderer a file-swap rather than a rewrite.

import { logger } from "@/lib/logger";
import { env } from "@/lib/env";
import { resolveCaptionTemplate } from "../../templateRegistry";
import { getKnownProviderLanguages } from "../../templateSync";
import { fromProviderWords, toProviderWords } from "../../words";
import type { CaptionRenderer } from "../../CaptionRenderer";
import {
  DEFAULT_CAPTION_EXPORT,
  type CaptionExportOptions,
  type CaptionRenderHandle,
  type CaptionRenderInput,
  type CaptionRenderState,
  type CaptionRendererHealth,
  type CaptionWord,
  type GetRenderContext,
} from "../../types";
import { SubmagicError } from "./SubmagicErrors";
import { mapProviderStatus } from "./statusMap";
import {
  createProject,
  exportProject,
  getProject,
  isSubmagicConfigured,
  submagicHealth,
  updateProjectWords,
} from "./SubmagicClient";
import type { SubmagicCreateProjectRequest, SubmagicProject } from "./SubmagicTypes";

/** Provider cap on custom-dictionary terms. Conservative — undocumented. */
const MAX_DICTIONARY_TERMS = 100;
const MAX_DICTIONARY_TERM_LEN = 40;

/**
 * Sanitises the caption vocabulary before it crosses the wire (§13).
 * Deduped case-insensitively, length-bounded, control characters stripped.
 */
export function sanitizeDictionary(terms: string[] | undefined): string[] {
  if (!Array.isArray(terms)) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of terms) {
    const term = String(raw).replace(/[\r\n\t]+/g, " ").trim().slice(0, MAX_DICTIONARY_TERM_LEN);
    if (!term) continue;
    const key = term.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(term);
    if (out.length >= MAX_DICTIONARY_TERMS) break;
  }
  return out;
}

/**
 * Picks the language code to send.
 *
 * Falls back to "auto" for anything the provider doesn't list. Notably there is
 * NO Hinglish code in their 127 languages — mixed Hindi/English content, which
 * is common for Clipiro's users, has to go as "hi", "en" or "auto", and the
 * quality of that is genuinely unverified (§34). Don't claim otherwise.
 */
async function resolveLanguage(requested: string): Promise<string> {
  if (!requested) return "auto";
  const known = await getKnownProviderLanguages();
  if (!known) return requested; // can't validate — send it and let the provider decide
  return known.has(requested) ? requested : "auto";
}

function outputUrlOf(p: SubmagicProject): string | undefined {
  return p.downloadUrl ?? p.outputUrl ?? undefined;
}

function wordsOf(p: SubmagicProject): CaptionWord[] {
  return fromProviderWords(p.words ?? p.transcript?.words);
}

export class SubmagicAdapter implements CaptionRenderer {
  readonly id = "submagic" as const;
  readonly paid = true;

  async createRender(input: CaptionRenderInput): Promise<CaptionRenderHandle> {
    const template = await resolveCaptionTemplate(input.templateId);
    if (!template?.providerTemplateId || template.provider !== "submagic") {
      // A caller reached us with a template we don't map. That's our bug, not
      // the user's, and it must never become a paid call.
      throw new SubmagicError(
        `template "${input.templateId}" is not mapped to a Submagic template`,
        "permanent",
        "VALIDATION_ERROR",
      );
    }

    const features = input.features ?? {};
    const body: SubmagicCreateProjectRequest = {
      title: `clipiro_${input.clipId}_${input.jobId}`.slice(0, 120),
      language: await resolveLanguage(input.language),
      videoUrl: input.sourceUrl,
      templateName: template.providerTemplateId,
      ...(input.position ? { captionPositionX: input.position.x, captionPositionY: input.position.y } : {}),
      // All of these overlap features Clipiro already owns (B-roll, silence
      // trimming, energy-reactive zoom, audio cleanup). Two systems editing the
      // same clip produce worse output than either alone, so they are off
      // unless a feature flag explicitly turns them on (§10/§30).
      magicZooms: features.autoZoom === true,
      magicBrolls: features.broll === true,
      removeBadTakes: features.removeBadTakes === true,
      cleanAudio: features.cleanAudio === true,
      // Hook TEXT is generated by Clipiro's own AI (§15) — the provider only
      // animates it. We never outsource the hook intelligence.
      hookTitle: input.hook?.enabled && input.hook.text ? input.hook.text : false,
      // Always false: the user edits captions before we pay to render (§12).
      autoRender: false,
      ...(input.webhookUrl ? { webhookUrl: input.webhookUrl } : {}),
    };

    // Sanitized here rather than at the call site, so every provider path gets
    // the same bounds no matter who assembles the input.
    const dictionary = sanitizeDictionary(input.dictionary);
    if (dictionary.length > 0) body.dictionary = dictionary;

    const project = await createProject(body);
    const providerJobId = project.id;
    if (!providerJobId) {
      // We were charged for a project we can't address. Unknown, not failed —
      // the sweep must not let anything spend again until this is understood.
      throw new SubmagicError(
        "submagic create returned no project id",
        "unknown_provider_state",
        "UNKNOWN",
      );
    }

    return {
      provider: this.id,
      providerJobId,
      status: mapProviderStatus(project.status, {
        exportRequested: false,
        hasOutput: Boolean(outputUrlOf(project)),
        current: "submitting",
      }) ?? "transcribing",
    };
  }

  /**
   * `current` and `exportRequested` come from OUR row, not the provider — the
   * same provider word ("completed") means different things before and after we
   * ask for a render, and an unrecognised status must hold position rather than
   * inventing a terminal state. See statusMap.ts.
   */
  async getRender(providerJobId: string, ctx?: GetRenderContext): Promise<CaptionRenderState> {
    const project = await getProject(providerJobId);
    const outputUrl = outputUrlOf(project);
    const current = ctx?.current ?? "transcribing";

    const mapped = mapProviderStatus(project.status, {
      exportRequested: ctx?.exportRequested ?? false,
      hasOutput: Boolean(outputUrl),
      current,
    });

    if (mapped === null && project.status) {
      logger.warn("submagic", `unrecognised provider status "${project.status}" — holding at ${current}`);
    }

    const duration = project.duration ?? project.durationSeconds;

    return {
      status: mapped ?? current,
      words: wordsOf(project),
      ...(outputUrl ? { outputUrl } : {}),
      ...(typeof duration === "number" && Number.isFinite(duration) ? { billableSeconds: duration } : {}),
      ...(project.error || project.errorMessage
        ? { failureCode: "PROVIDER_ERROR", failureMessage: String(project.error ?? project.errorMessage).slice(0, 500) }
        : {}),
      raw: project,
    };
  }

  async updateTranscript(providerJobId: string, words: CaptionWord[]): Promise<void> {
    // Complete array, in chronological order — the provider's documented
    // editing flow replaces rather than patches. Callers must have already
    // persisted to Clip.transcriptJson, so a failure here loses nothing.
    await updateProjectWords(providerJobId, toProviderWords(words));
  }

  async exportRender(providerJobId: string, options?: CaptionExportOptions): Promise<CaptionRenderHandle> {
    const project = await exportProject(providerJobId, { ...DEFAULT_CAPTION_EXPORT, ...options });
    return {
      provider: this.id,
      providerJobId,
      status: mapProviderStatus(project.status, {
        exportRequested: true,
        hasOutput: Boolean(outputUrlOf(project)),
        current: "rendering",
      }) ?? "rendering",
    };
  }

  async health(): Promise<CaptionRendererHealth> {
    return submagicHealth();
  }
}

export function isSubmagicUsable(): boolean {
  return isSubmagicConfigured() && Boolean(env.SUBMAGIC_API_KEY);
}

export const submagicAdapter = new SubmagicAdapter();
