#!/usr/bin/env node
// Builds `.ds-pkg/` — a sync-only package view of app/components/ui — so the
// design-sync converter can treat Clipiro's in-app component library like a
// published one. Nothing here is reimplemented: the barrel re-exports the real
// source files, the .d.ts files are tsc's own emit from them, and the CSS is
// Tailwind's compile of the real app/globals.css.
//
//   node .design-sync/build-pkg.mjs        (cfg.buildCmd; run from repo root)
//
// Output (.ds-pkg/, gitignored, regenerated every run):
//   package.json     name/version/entry/types for the converter
//   index.ts         barrel: `export * from` every ui/ source file
//   types/           tsc declaration emit (the props contract the agent codes to)
//   styles.css       compiled Tailwind + the emerald theme applied at :root

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const UI = join(ROOT, "app/components/ui");
const OUT = join(ROOT, ".ds-pkg");

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

// -- 1. barrel ---------------------------------------------------------------
const sources = readdirSync(UI)
  .filter((f) => /\.(tsx?|jsx?)$/.test(f) && !/\.(test|spec|stories)\./.test(f) && !/\.d\.ts$/.test(f))
  .sort();
// `export *` does NOT carry a module's default export, so a component written
// as `export default function Breadcrumbs` would silently vanish from the
// bundle. Re-export each default under its declared name as well.
const lines = [];
for (const f of sources) {
  const spec = `../app/components/ui/${f.replace(/\.(tsx?|jsx?)$/, "")}`;
  lines.push(`export * from "${spec}";`);
  const def = readFileSync(join(UI, f), "utf8").match(/export\s+default\s+(?:async\s+)?(?:function|class)\s+([A-Z]\w*)/);
  if (def) lines.push(`export { default as ${def[1]} } from "${spec}";`);
}
writeFileSync(join(OUT, "index.ts"), "// Generated by .design-sync/build-pkg.mjs — do not edit.\n" + lines.join("\n") + "\n");

// -- 2. package.json ---------------------------------------------------------
const repoPkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
writeFileSync(
  join(OUT, "package.json"),
  JSON.stringify(
    {
      name: "@clipiro/ui",
      version: repoPkg.version ?? "0.0.0",
      private: true,
      module: "index.ts",
      types: "types/.ds-pkg/index.d.ts",
    },
    null,
    2,
  ) + "\n",
);

// -- 3. declarations ---------------------------------------------------------
// tsc exits non-zero on any type error anywhere in the reachable graph, but
// still emits (noEmitOnError: false). Judge by the output, not the exit code.
const tsc = join(ROOT, "node_modules/typescript/bin/tsc");
try {
  execFileSync(process.execPath, [tsc, "-p", join(ROOT, ".design-sync/tsconfig.dts.json")], { stdio: "pipe" });
} catch (e) {
  const out = `${e.stdout ?? ""}${e.stderr ?? ""}`.trim();
  if (out) console.error(`  tsc reported (declarations still emitted):\n${out.split("\n").slice(0, 20).join("\n")}`);
}
const typesEntry = join(OUT, "types/.ds-pkg/index.d.ts");
if (!existsSync(typesEntry)) {
  console.error(`✗ declaration emit produced no ${typesEntry}`);
  process.exit(1);
}

// -- 4. styles ---------------------------------------------------------------
const globalsPath = join(ROOT, "app/globals.css");
const compiled = (
  await postcss([tailwind({ base: ROOT })]).process(readFileSync(globalsPath, "utf8"), { from: globalsPath })
).css;

// Clipiro is dark-first with no light mode: the app puts `theme-emerald` on
// <body>, and the light values in :root are migration scaffolding. A design
// rendered from this bundle has no Clipiro <body>, so make every emerald rule
// also match :root by rewriting its selector to `:is(:root, .theme-emerald)`.
//
// Rewriting rather than extracting is deliberate. The compiled block nests
// `@supports (color: color-mix(...))` overrides inside itself, and carries
// child rules (::selection, autofill, scrollbars). An earlier version copied
// the declarations out by splitting on `;` — which kept the plain fallbacks,
// dropped the nested real values, and silently lost every variable following a
// nested block (--accent-violet, --gradient-brand), leaking the retired violet
// brand into ConfirmDialog and EmptyState.
//
// `:is()` takes its most specific argument, so this is (0,1,0) — equal to the
// light `:root` — and wins by source order: compiled globals.css emits the
// light :root before the emerald blocks, both unlayered. Checked below.
const lightRootAt = compiled.search(/^:root\s*\{[^}]*--bg:\s*#fff/m);
const emeraldAt = compiled.indexOf(".theme-emerald {");
if (emeraldAt < 0) {
  console.error("✗ no .theme-emerald block in compiled globals.css — the theme moved; update build-pkg.mjs");
  process.exit(1);
}
if (lightRootAt > emeraldAt) {
  console.error("✗ light :root now follows .theme-emerald in compiled CSS — the :root rewrite would lose; update build-pkg.mjs");
  process.exit(1);
}
const themed = compiled.replace(/\.theme-emerald(?![\w-])/g, ":is(:root, .theme-emerald)");
const vars = (themed.match(/:is\(:root, \.theme-emerald\)/g) ?? []);

// Editor caption fonts are self-hosted at absolute /fonts/* URLs that only
// resolve on clipiro.com and are used only by the editor (its own token set,
// excluded from this system). Drop them rather than ship dangling faces.
const withoutEditorFonts = themed.replace(/@font-face\s*\{[^}]*url\(\s*["']?\/fonts\/[^}]*\}/g, "");

// Geist comes from next/font in the app, which defines --font-geist-sans on
// <html> at runtime. The variables are defined below; the faces themselves
// ship as local files via cfg.extraFonts (.design-sync/fonts/geist.css) — see
// that file for why local beats a Google Fonts @import here.
const FONTS = "";
const ROOT_THEME =
  "\n/* design-sync: next/font's runtime variables + the app <body>'s bg/fg classes */\n" +
  ":root {\n" +
  '  --font-geist-sans: "Geist", ui-sans-serif, system-ui, sans-serif;\n' +
  '  --font-geist-mono: "Geist Mono", ui-monospace, SFMono-Regular, monospace;\n}\n' +
  // `html body`, not `body`: the design-sync preview card injects its own
  // `body{background:#fff}` AFTER this stylesheet, and would otherwise put
  // every dark-theme component on a white panel. (0,0,2) beats it on
  // specificity regardless of order. Clipiro has no light mode to preserve.
  "html body {\n  background-color: var(--canvas);\n  color: var(--on-canvas);\n}\n";

writeFileSync(join(OUT, "styles.css"), FONTS + withoutEditorFonts + ROOT_THEME);

console.error(
  `✓ .ds-pkg: ${sources.length} sources, ${vars.length} emerald selectors rewritten to also match :root, ` +
    `styles.css ${Math.round((FONTS + withoutEditorFonts + ROOT_THEME).length / 1024)} KB`,
);
