// Provider-agnostic caption-rendering vocabulary.
//
// AutoClip must never learn which provider is underneath. Everything in this
// file is Clipiro's own model: our template slugs, our status names, our word
// shape. Adapters translate to and from a provider's dialect and nothing else
// in the app sees it.
//
// UNITS: every time in this module is MILLISECONDS, matching WordTiming in
// utils/elevenlabs.ts and Clip.transcriptJson. Clip columns (startSec/endSec/
// durationSec) are seconds. That boundary has already caused one bug in this
// codebase (see wordsToCaptionCues in lib/editor/caption-generation.ts), so
// conversions live in exactly one place per adapter and are never inlined.

export type CaptionRendererId = "native" | "submagic";

/**
 * Clipiro's own render lifecycle. Provider states are mapped INTO these inside
 * the adapter (see providers/submagic/statusMap.ts) so a provider renaming a
 * status, or a new provider with entirely different names, never reaches the
 * database or the UI.
 *
 * Stored as a plain String column — this schema keeps small closed string sets
 * as TEXT + app-level validation rather than a Postgres enum (there is exactly
 * one enum in prisma/schema.prisma, `Role`).
 *
 * Terminal: completed | failed | cancelled.
 * `needs_reconciliation` is deliberately NOT terminal — it means we do not know
 * what the provider did (see UNKNOWN_PROVIDER_STATE in SubmagicErrors.ts) and
 * must ask before spending money again.
 */
export const CAPTION_RENDER_STATUSES = [
  "queued",
  "submitting",
  "transcribing",
  "ready_to_edit",
  "editing",
  "export_queued",
  "rendering",
  "downloading",
  "uploading",
  "completed",
  "failed",
  "cancelled",
  "needs_reconciliation",
] as const;

export type CaptionRenderStatus = (typeof CAPTION_RENDER_STATUSES)[number];

export const TERMINAL_CAPTION_STATUSES: readonly CaptionRenderStatus[] = [
  "completed",
  "failed",
  "cancelled",
];

export function isTerminalCaptionStatus(s: CaptionRenderStatus): boolean {
  return TERMINAL_CAPTION_STATUSES.includes(s);
}

// ── Words ───────────────────────────────────────────────────────────────────

export type CaptionWordType = "word" | "punctuation" | "silence";

/**
 * One caption token. Richer than utils/elevenlabs.ts's WordTiming because
 * providers that let you edit captions need to round-trip punctuation and
 * silence as first-class tokens, not just spoken words.
 *
 * `id` is the PROVIDER's id for this token when it has one — carried so an
 * update can address existing tokens instead of replacing the whole list, and
 * dropped entirely when talking to a provider that doesn't use ids.
 */
export interface CaptionWord {
  id?: string;
  text: string;
  type: CaptionWordType;
  /** ms from the start of the clip. */
  startTime: number;
  /** ms from the start of the clip. */
  endTime: number;
}

// ── Render inputs ───────────────────────────────────────────────────────────

/** 0–100, percent of frame. Clipiro stores these; the provider is told them. */
export interface CaptionPosition {
  x: number;
  y: number;
}

export interface CaptionHook {
  enabled: boolean;
  /** Generated by Clipiro's own AI, never by the rendering provider. */
  text: string;
  style?: string;
  position?: CaptionPosition;
  size?: number;
}

/**
 * Optional provider effects that OVERLAP features Clipiro already owns.
 * All default false; each is gated by its own feature flag. Enabling them is a
 * deliberate product decision, not a default, because Clipiro's own B-roll,
 * silence removal and zoom would otherwise fight the provider's.
 */
export interface CaptionFeatureToggles {
  autoZoom?: boolean;
  broll?: boolean;
  cleanAudio?: boolean;
  removeBadTakes?: boolean;
}

export interface CaptionRenderInput {
  /** Our CaptionRenderJob id — used for the provider-side title and correlation. */
  jobId: string;
  clipId: string;
  /**
   * A short-lived presigned URL the provider downloads the clip from. Minted
   * per use, never persisted (see docs/autoclip-p0-3-production-incident.md).
   */
  sourceUrl: string;
  /** Clipiro template slug, e.g. "viral-bold-01". Never a provider name. */
  templateId: string;
  /** BCP-47-ish code, or "auto". Validated against the provider's list. */
  language: string;
  durationSec: number;
  position?: CaptionPosition;
  hook?: CaptionHook | null;
  features?: CaptionFeatureToggles;
  /**
   * Custom vocabulary — proper nouns and jargon the speech model gets wrong
   * (§13). Sanitized and capped by the adapter before it crosses the wire.
   */
  dictionary?: string[];
  /** Absolute callback URL; omitted when the provider can't call us back. */
  webhookUrl?: string;
}

export interface CaptionExportOptions {
  width?: number;
  height?: number;
  fps?: number;
}

/** Reels/Shorts default (§16). */
export const DEFAULT_CAPTION_EXPORT: Required<CaptionExportOptions> = {
  width: 1080,
  height: 1920,
  fps: 30,
};

// ── Render outputs ──────────────────────────────────────────────────────────

export interface CaptionRenderHandle {
  provider: CaptionRendererId;
  /** The provider's own job/project id. Never exposed to the frontend. */
  providerJobId: string;
  status: CaptionRenderStatus;
}

export interface CaptionRenderState {
  status: CaptionRenderStatus;
  /** Present once the provider has transcribed. */
  words?: CaptionWord[];
  /** Present once a render has finished — a provider-hosted URL we then ingest. */
  outputUrl?: string;
  /** Provider-reported billable seconds, when it tells us. */
  billableSeconds?: number;
  failureCode?: string;
  failureMessage?: string;
  /** Raw payload, stored for support/debugging. Never returned to a client. */
  raw?: unknown;
}

export interface CaptionRendererHealth {
  configured: boolean;
  reachable: boolean;
  breakerOpen: boolean;
}

/**
 * What the caller knows that the provider's status string alone can't express.
 *
 * With auto-render disabled a job has two distinct "done" moments — done
 * transcribing and done rendering — and providers commonly spell both
 * "completed". Passing our own view of the job lets the adapter disambiguate,
 * and lets an unrecognised status hold its current position instead of being
 * guessed into a terminal state.
 */
export interface GetRenderContext {
  /** True once exportRender has been called for this job. */
  exportRequested?: boolean;
  /** The status stored on our row right now. */
  current?: CaptionRenderStatus;
}
