import { ImageModelEntry } from "./types";

// Adding a model only requires adding an entry here — no other file needs to change
// (app/api/tools/image-generator/route.ts and app/components/ImageGeneratorTool.tsx both
// read this registry generically). Credit costs are rough placeholders reflecting relative
// FAL pricing tiers; adjust to match actual billed usage before shipping.
export const IMAGE_MODELS: readonly ImageModelEntry[] = [
  {
    id: "gemini-flash-2.0",
    displayName: "Gemini Flash 2.0",
    provider: "Google",
    badge: "Google",
    category: "image",
    integration: "direct-gemini",
    creditCost: 1,
    supportedParameters: ["prompt"],
    defaultValues: {},
    imageInput: "none",
  },
  {
    id: "seedream-5.0",
    displayName: "Seedream 5.0",
    provider: "ByteDance",
    badge: "ByteDance",
    category: "image",
    integration: "fal",
    falEndpoint: "bytedance/seedream/v5/lite/text-to-image",
    creditCost: 2,
    supportedParameters: ["prompt", "negativePrompt", "aspectRatio", "seed"],
    defaultValues: { aspectRatio: "1:1" },
    inputMap: { negativePrompt: "negative_prompt", aspectRatio: "aspect_ratio" },
    resultPath: ["images.0.url", "image.url"],
    imageInput: "none",
  },
  {
    id: "gpt-image-2",
    displayName: "GPT Image 2",
    provider: "OpenAI",
    badge: "OpenAI",
    category: "image",
    integration: "fal",
    falEndpoint: "openai/gpt-image-2",
    creditCost: 6,
    supportedParameters: ["prompt", "aspectRatio"],
    defaultValues: { aspectRatio: "1:1" },
    inputMap: { aspectRatio: "aspect_ratio" },
    resultPath: ["images.0.url", "image.url"],
    imageInput: "none",
  },
  {
    id: "flux-2",
    displayName: "Flux 2",
    provider: "Black Forest Labs",
    badge: "Flux",
    category: "image",
    integration: "fal",
    falEndpoint: "fal-ai/flux-2-pro",
    creditCost: 3,
    supportedParameters: ["prompt", "aspectRatio", "seed", "guidanceScale", "steps"],
    defaultValues: { aspectRatio: "1:1" },
    inputMap: { aspectRatio: "aspect_ratio", guidanceScale: "guidance_scale", steps: "num_inference_steps" },
    resultPath: ["images.0.url", "image.url"],
    imageInput: "none",
  },
  {
    id: "nano-banana-2",
    displayName: "Nano Banana 2",
    provider: "Google",
    badge: "Google",
    category: "image",
    integration: "fal",
    falEndpoint: "fal-ai/nano-banana-2",
    creditCost: 2,
    supportedParameters: ["prompt", "aspectRatio"],
    defaultValues: { aspectRatio: "1:1" },
    inputMap: { aspectRatio: "aspect_ratio" },
    resultPath: ["images.0.url", "image.url"],
    imageInput: "none",
  },
  {
    id: "ideogram-4",
    displayName: "Ideogram 4",
    provider: "Ideogram",
    badge: "Ideogram",
    category: "image",
    integration: "fal",
    // TODO verify-before-ship: confirm exact tier slug (`/fast` vs `/instant`).
    falEndpoint: "ideogram/v4/fast",
    creditCost: 3,
    supportedParameters: ["prompt", "negativePrompt", "aspectRatio", "seed"],
    defaultValues: { aspectRatio: "1:1" },
    inputMap: { negativePrompt: "negative_prompt", aspectRatio: "aspect_ratio" },
    resultPath: ["images.0.url", "image.url"],
    imageInput: "none",
  },
  {
    id: "krea-2",
    displayName: "Krea 2",
    provider: "Krea",
    badge: "Krea",
    category: "image",
    integration: "fal",
    falEndpoint: "fal-ai/krea-2/turbo",
    creditCost: 2,
    supportedParameters: ["prompt", "aspectRatio", "seed"],
    defaultValues: { aspectRatio: "1:1" },
    inputMap: { aspectRatio: "aspect_ratio" },
    resultPath: ["images.0.url", "image.url"],
    imageInput: "none",
  },
  {
    id: "nano-banana-pro",
    displayName: "Nano Banana Pro",
    provider: "Google",
    badge: "Google",
    category: "image",
    integration: "fal",
    falEndpoint: "fal-ai/nano-banana-pro",
    creditCost: 4,
    supportedParameters: ["prompt", "aspectRatio"],
    defaultValues: { aspectRatio: "1:1" },
    inputMap: { aspectRatio: "aspect_ratio" },
    resultPath: ["images.0.url", "image.url"],
    imageInput: "none",
  },
  {
    id: "qwen-image-2.0",
    displayName: "Qwen Image 2.0",
    provider: "Alibaba",
    badge: "Qwen",
    category: "image",
    integration: "fal",
    falEndpoint: "fal-ai/qwen-image-2/text-to-image",
    creditCost: 1,
    supportedParameters: ["prompt", "negativePrompt", "aspectRatio", "seed", "guidanceScale"],
    defaultValues: { aspectRatio: "1:1" },
    inputMap: { negativePrompt: "negative_prompt", aspectRatio: "image_size", guidanceScale: "cfg_scale" },
    resultPath: ["images.0.url", "image.url"],
    imageInput: "none",
  },
] as const;

export const DEFAULT_IMAGE_MODEL_ID = "gemini-flash-2.0";
export type ImageModelId = typeof IMAGE_MODELS[number]["id"];

export function getImageModel(id: string | undefined | null): ImageModelEntry {
  return IMAGE_MODELS.find((m) => m.id === id) ?? IMAGE_MODELS.find((m) => m.id === DEFAULT_IMAGE_MODEL_ID)!;
}
