// GENERATED by scripts/process-tool-shots.ts — do not edit by hand.
//
// Measured dimensions and blur placeholders for the tool screenshots under
// public/tools/. Alt text is deliberately not here: it is prose, lives with
// the rest of the copy in app/tools/content.ts, and would be lost every time
// the shots were re-captured.

export interface ToolShotFile {
  src: string;
  width: number;
  height: number;
  /** Tiny inline WebP shown by next/image while the full file loads. */
  blurDataURL: string;
}

export interface ToolShotFiles {
  ready: ToolShotFile;
  /** Absent for tools with no second state worth photographing. */
  result?: ToolShotFile;
}

export const TOOL_SHOT_FILES: Record<string, ToolShotFiles> = {
  "ai-brainstormer": {
    ready: {
      src: "/tools/ai-brainstormer-ready.webp",
      width: 2200,
      height: 944,
      blurDataURL:
        "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAACwAQCdASoQAAcAA4BaJZwAAudfJY+AAP735H4+Z6jgAA==",
    },
    result: {
      src: "/tools/ai-brainstormer-result.webp",
      width: 2200,
      height: 1221,
      blurDataURL:
        "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACwAQCdASoQAAkAA4BaJZwAAudgSNWAAP735IZ84Hs/GRSCooAAAA==",
    },
  },
  "ai-image-generator": {
    ready: {
      src: "/tools/ai-image-generator-ready.webp",
      width: 2200,
      height: 1375,
      blurDataURL:
        "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAoAA4BaJaQAAuukEnLAAAD+9wuqnj8gU8PvcwE5SFmQ43nktFutOy1btjNGPyj0AAAA",
    },
    result: {
      src: "/tools/ai-image-generator-result.webp",
      width: 2200,
      height: 1375,
      blurDataURL:
        "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAoAA4BaJYgAAuukEnHqUJAA/vcLqp4/IFPD73MBOUhZkON55LRbrTstW7YzRkAUAPb40dIxJrvv61vw6j/g7fGAAA==",
    },
  },
  "ai-voiceover": {
    ready: {
      src: "/tools/ai-voiceover-ready.webp",
      width: 2200,
      height: 1239,
      blurDataURL:
        "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoQAAkAA4BaJaQAA3AA/vRyMBU8mIlgAAA=",
    },
    result: {
      src: "/tools/ai-voiceover-result.webp",
      width: 2200,
      height: 1239,
      blurDataURL:
        "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoQAAkAA4BaJZwAAubd4X6gAP73Ej6tW59OhZOyKpXWQRPuYUusAA==",
    },
  },
  "mp3-converter": {
    ready: {
      src: "/tools/mp3-converter-ready.webp",
      width: 2200,
      height: 1375,
      blurDataURL:
        "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoQAAoAA4BaJaQAA3AA/vRmAAA=",
    },
  },
};
