// Derived scores. All deterministic — the AI layer narrates these numbers, it
// never produces them. A score generated by a language model would be worthless.
//
// Every score here refuses to guess: below its minimum sample size it returns
// null and the UI says so, rather than showing a confident number computed from
// three data points.

import { postAudience, postEngagementRate, postShareRate } from "./posts";
import { mad, median, percentileRank } from "./series";
import type { PostRow } from "./types";

/** Below this many comparable posts, a viral score is noise. */
export const MIN_VIRAL_COHORT = 5;

/** Logistic squash, so extreme outliers compress instead of pinning at 100. */
function logistic(z: number): number {
  return 1 / (1 + Math.exp(-z));
}

/**
 * A post's cohort: the account's trailing 90 days of the SAME media type.
 * Comparing a Short against a long-form upload would say more about the format
 * than about the post. Falls back to all types when a type is too rare to
 * compare within.
 */
export function viralCohort(post: PostRow, history: PostRow[], now: Date, windowDays = 90): PostRow[] {
  const cutoff = now.getTime() - windowDays * 86_400_000;
  const recent = history.filter(
    (p) => p.id !== post.id && p.publishedAt instanceof Date && p.publishedAt.getTime() >= cutoff,
  );
  const sameType = recent.filter((p) => (p.mediaType || "other") === (post.mediaType || "other"));
  return sameType.length >= MIN_VIRAL_COHORT ? sameType : recent;
}

/**
 * Viral score, 0–100.
 *
 * Robust z-score of log audience against the cohort (log because reach is
 * heavy-tailed; MAD rather than stddev because one genuine viral hit would
 * otherwise inflate the spread and flatten every subsequent score), blended
 * with share-rate and engagement-rate percentiles.
 *
 * Weights: 0.55 reach outlier / 0.25 share rate / 0.20 engagement rate. Shares
 * are weighted above engagement because sharing is what actually drives
 * distribution.
 *
 * Returns null below MIN_VIRAL_COHORT comparable posts.
 */
export function viralScore(post: PostRow, cohort: PostRow[]): number | null {
  if (cohort.length < MIN_VIRAL_COHORT) return null;

  const audience = postAudience(post);
  if (audience === null) return null;

  const cohortAudience = cohort.map(postAudience).filter((v): v is number => v !== null);
  if (cohortAudience.length < MIN_VIRAL_COHORT) return null;

  const logs = cohortAudience.map((v) => Math.log1p(v));
  const medianLog = median(logs)!;
  const madLog = mad(logs) ?? 0;
  // 1.4826 scales MAD to be comparable with a standard deviation under normality.
  const scale = madLog > 0 ? madLog * 1.4826 : 1;
  const z = (Math.log1p(audience) - medianLog) / scale;

  const shareRate = postShareRate(post);
  const cohortShareRates = cohort.map(postShareRate).filter((v): v is number => v !== null);
  const sharePct =
    shareRate !== null && cohortShareRates.length >= MIN_VIRAL_COHORT
      ? (percentileRank(cohortShareRates, shareRate) ?? 0.5)
      : 0.5; // unknown → neutral, never a penalty

  const er = postEngagementRate(post);
  const cohortErs = cohort.map(postEngagementRate).filter((v): v is number => v !== null);
  const erPct =
    er !== null && cohortErs.length >= MIN_VIRAL_COHORT ? (percentileRank(cohortErs, er) ?? 0.5) : 0.5;

  const blended = 0.55 * logistic(z) + 0.25 * sharePct + 0.2 * erPct;
  return Math.round(Math.max(0, Math.min(100, blended * 100)) * 10) / 10;
}

export interface PostScoreComponents {
  /** 0–100 overall. */
  score: number;
  /** Each 0–100, so the UI can explain the total instead of asserting it. */
  reach: number;
  engagement: number;
  shares: number;
  retention: number | null;
  /** Fraction of the weighting actually available, 0–1. */
  confidence: number;
}

/**
 * The "AI performance score" for a post — computed here, narrated by the model.
 *
 * Components are returned separately so the UI (and the model) can say WHICH
 * part drove the number. Missing components redistribute their weight rather
 * than counting as zero, which would punish a post for a metric its platform
 * does not report.
 */
export function postScoreComponents(post: PostRow, cohort: PostRow[]): PostScoreComponents | null {
  if (cohort.length < MIN_VIRAL_COHORT) return null;

  const pctOf = (
    value: number | null,
    extract: (p: PostRow) => number | null,
  ): number | null => {
    if (value === null) return null;
    const values = cohort.map(extract).filter((v): v is number => v !== null);
    if (values.length < MIN_VIRAL_COHORT) return null;
    const rank = percentileRank(values, value);
    return rank === null ? null : rank * 100;
  };

  const reach = pctOf(postAudience(post), postAudience);
  const engagement = pctOf(postEngagementRate(post), postEngagementRate);
  const shares = pctOf(postShareRate(post), postShareRate);
  const retention = pctOf(post.avgViewPercentage ?? null, (p) => p.avgViewPercentage ?? null);

  const parts: Array<{ value: number | null; weight: number }> = [
    { value: reach, weight: 0.35 },
    { value: engagement, weight: 0.3 },
    { value: shares, weight: 0.2 },
    { value: retention, weight: 0.15 },
  ];

  const available = parts.filter((p) => p.value !== null);
  if (available.length === 0) return null;

  const totalWeight = available.reduce((s, p) => s + p.weight, 0);
  const score = available.reduce((s, p) => s + p.value! * (p.weight / totalWeight), 0);

  return {
    score: Math.round(score * 10) / 10,
    reach: reach ?? 0,
    engagement: engagement ?? 0,
    shares: shares ?? 0,
    retention,
    // Rounded: summing float weights gives 0.9999999999999999 for a full set,
    // which reads as "incomplete data" to any caller comparing against 1.
    confidence: Math.round(totalWeight * 100) / 100,
  };
}

export interface HealthComponent {
  key: "growth" | "engagement" | "consistency" | "retention" | "completeness";
  /** 0–100, or null when the inputs are unavailable. */
  value: number | null;
  weight: number;
  label: string;
}

export interface AccountHealth {
  /** 0–100. */
  score: number;
  components: HealthComponent[];
  /** Fraction of the weighting that had data, 0–1. Low means "treat with care". */
  confidence: number;
}

export interface HealthInputs {
  /** Follower growth over the window, as a percentage. */
  growthRatePct: number | null;
  /** Current engagement rate, percent. */
  engagementRate: number | null;
  /** The account's own trailing engagement rate, percent. */
  baselineEngagementRate: number | null;
  /** 0–100 from postingConsistency. */
  consistencyScore: number | null;
  /** Average view percentage, or reach ÷ followers × 100 where that is the honest proxy. */
  retentionPct: number | null;
  /** Fraction of expected metrics this account actually supplies, 0–1. */
  dataCompleteness: number | null;
}

const clamp100 = (v: number) => Math.max(0, Math.min(100, v));

/**
 * Account health, 0–100, from five explicitly-returned components.
 *
 * The components matter as much as the total: an opaque score is not actionable,
 * and "your consistency is 30" is. Missing components redistribute their weight
 * proportionally and lower `confidence`, so an account whose platform reports
 * little is not scored as unhealthy for that reason.
 */
export function accountHealth(inputs: HealthInputs): AccountHealth {
  // Growth: 0%/period → 50, +10% → 100, -10% → 0. Linear in between.
  const growth =
    inputs.growthRatePct === null ? null : clamp100(50 + inputs.growthRatePct * 5);

  // Engagement measured against the account's OWN baseline, not an industry band
  // — for a creator who has never been near the industry average, that is the
  // only comparison that means anything.
  const engagement =
    inputs.engagementRate === null || inputs.baselineEngagementRate === null || inputs.baselineEngagementRate <= 0
      ? null
      : clamp100((inputs.engagementRate / inputs.baselineEngagementRate) * 50);

  const consistency = inputs.consistencyScore === null ? null : clamp100(inputs.consistencyScore);
  const retention = inputs.retentionPct === null ? null : clamp100(inputs.retentionPct);
  const completeness = inputs.dataCompleteness === null ? null : clamp100(inputs.dataCompleteness * 100);

  const components: HealthComponent[] = [
    { key: "growth", value: growth, weight: 0.25, label: "Growth momentum" },
    { key: "engagement", value: engagement, weight: 0.25, label: "Engagement vs your baseline" },
    { key: "consistency", value: consistency, weight: 0.2, label: "Posting consistency" },
    { key: "retention", value: retention, weight: 0.15, label: "Audience retention" },
    { key: "completeness", value: completeness, weight: 0.15, label: "Data completeness" },
  ];

  const available = components.filter((c) => c.value !== null);
  if (available.length === 0) return { score: 0, components, confidence: 0 };

  const totalWeight = available.reduce((s, c) => s + c.weight, 0);
  const score = available.reduce((s, c) => s + c.value! * (c.weight / totalWeight), 0);

  return {
    score: Math.round(score * 10) / 10,
    components,
    confidence: Math.round(totalWeight * 100) / 100,
  };
}
