/**
 * Turns the raw PNGs from scripts/capture-tool-shots.ts into the optimized
 * WebP the marketing pages serve, and prints the registry block to paste into
 * app/tools/content.ts.
 *
 *   npx tsx scripts/process-tool-shots.ts                # everything captured
 *   npx tsx scripts/process-tool-shots.ts ai-voiceover   # one or more slugs
 *
 * In:  .tool-shots/<slug>-{ready,result}.png   (2x, gitignored)
 * Out: public/tools/<slug>-{ready,result}.webp (committed)
 */
import { readdir, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const IN_DIR = path.resolve(process.cwd(), ".tool-shots");
const OUT_DIR = path.resolve(process.cwd(), "public", "tools");

/** Displayed at ~1100px inside the device frame, so 2200 covers retina. */
const MAX_WIDTH = 2200;
const QUALITY = 90;

interface Processed {
  slug: string;
  shot: "ready" | "result";
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
  bytes: number;
}

// Not named `process` — that shadows the global and breaks process.cwd().
async function processShot(file: string): Promise<Processed | null> {
  const match = /^(.+)-(ready|result)\.png$/.exec(path.basename(file));
  if (!match) return null;
  const slug = match[1];
  const shot = match[2] as "ready" | "result";

  const input = sharp(path.join(IN_DIR, file));
  const meta = await input.metadata();
  const targetWidth = Math.min(meta.width ?? MAX_WIDTH, MAX_WIDTH);

  const outName = `${slug}-${shot}.webp`;
  const outPath = path.join(OUT_DIR, outName);
  const info = await input
    .resize({ width: targetWidth, withoutEnlargement: true })
    .webp({ quality: QUALITY })
    .toFile(outPath);

  // A 16px-wide blur stands in while the full image loads. next/image needs it
  // as a data URI; nothing in the repo generated one before, so this is the
  // first use of placeholder="blur".
  const blur = await sharp(path.join(IN_DIR, file))
    .resize({ width: 16 })
    .webp({ quality: 40 })
    .toBuffer();

  return {
    slug,
    shot,
    src: `/tools/${outName}`,
    width: info.width,
    height: info.height,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    bytes: info.size,
  };
}

/**
 * Emits app/tools/shots.ts.
 *
 * Only the measured file data lives here, never the alt text — that is prose,
 * belongs with the rest of the copy in content.ts, and must survive a
 * re-capture. This file is safe to overwrite wholesale.
 */
function shotsModule(rows: Processed[]): string {
  const bySlug = new Map<string, Partial<Record<"ready" | "result", Processed>>>();
  for (const row of rows) {
    const entry = bySlug.get(row.slug) ?? {};
    entry[row.shot] = row;
    bySlug.set(row.slug, entry);
  }

  const lines: string[] = [
    "// GENERATED by scripts/process-tool-shots.ts — do not edit by hand.",
    "//",
    "// Measured dimensions and blur placeholders for the tool screenshots under",
    "// public/tools/. Alt text is deliberately not here: it is prose, lives with",
    "// the rest of the copy in app/tools/content.ts, and would be lost every time",
    "// the shots were re-captured.",
    "",
    "export interface ToolShotFile {",
    "  src: string;",
    "  width: number;",
    "  height: number;",
    "  /** Tiny inline WebP shown by next/image while the full file loads. */",
    "  blurDataURL: string;",
    "}",
    "",
    "export interface ToolShotFiles {",
    "  ready: ToolShotFile;",
    "  /** Absent for tools with no second state worth photographing. */",
    "  result?: ToolShotFile;",
    "}",
    "",
    "export const TOOL_SHOT_FILES: Record<string, ToolShotFiles> = {",
  ];

  for (const [slug, shots] of [...bySlug].sort()) {
    lines.push(`  "${slug}": {`);
    for (const shot of ["ready", "result"] as const) {
      const s = shots[shot];
      if (!s) continue;
      lines.push(`    ${shot}: {`);
      lines.push(`      src: "${s.src}",`);
      lines.push(`      width: ${s.width},`);
      lines.push(`      height: ${s.height},`);
      lines.push(`      blurDataURL:`);
      lines.push(`        "${s.blurDataURL}",`);
      lines.push(`    },`);
    }
    lines.push(`  },`);
  }

  lines.push("};", "");
  return lines.join("\n");
}

/** Reads back whatever shots.ts already declares, so partial runs merge. */
async function loadExisting(): Promise<Map<string, Partial<Record<"ready" | "result", Processed>>>> {
  const out = new Map<string, Partial<Record<"ready" | "result", Processed>>>();
  try {
    const mod = await import(path.resolve(process.cwd(), "app", "tools", "shots.ts"));
    for (const [slug, shots] of Object.entries(mod.TOOL_SHOT_FILES as Record<string, Record<string, ToolShotFileLike>>)) {
      const entry: Partial<Record<"ready" | "result", Processed>> = {};
      for (const shot of ["ready", "result"] as const) {
        const f = shots[shot];
        if (f) entry[shot] = { slug, shot, bytes: 0, ...f };
      }
      out.set(slug, entry);
    }
  } catch {
    // First run — the module does not exist yet.
  }
  return out;
}

interface ToolShotFileLike {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
}

async function main() {
  const wanted = process.argv.slice(2);
  await mkdir(OUT_DIR, { recursive: true });

  const files = (await readdir(IN_DIR))
    .filter((f) => f.endsWith(".png"))
    .filter((f) => !wanted.length || wanted.some((slug) => f.startsWith(`${slug}-`)));

  if (!files.length) {
    console.error(`No PNGs in ${path.relative(process.cwd(), IN_DIR)}. Run capture-tool-shots.ts first.`);
    process.exit(1);
  }

  const rows: Processed[] = [];
  for (const file of files.sort()) {
    const result = await processShot(file);
    if (!result) continue;
    rows.push(result);
    const kb = (result.bytes / 1024).toFixed(0);
    const warn = result.bytes > 250_000 ? "  <-- over 250KB" : "";
    console.log(`  ${result.src.padEnd(42)} ${result.width}x${result.height}  ${kb.padStart(4)} KB${warn}`);
  }

  // Merge rather than overwrite: a partial run (one slug) must not drop the
  // other tools' entries from the module.
  const existing = await loadExisting();
  for (const row of rows) {
    const entry = existing.get(row.slug) ?? {};
    entry[row.shot] = row;
    existing.set(row.slug, entry);
  }
  const merged = [...existing.values()].flatMap((e) => [e.ready, e.result].filter(Boolean) as Processed[]);

  const generated = path.resolve(process.cwd(), "app", "tools", "shots.ts");
  await writeFile(generated, shotsModule(merged));

  const total = rows.reduce((sum, r) => sum + r.bytes, 0);
  console.log(`\n${rows.length} images, ${(total / 1024).toFixed(0)} KB total`);
  console.log(`Wrote ${path.relative(process.cwd(), generated)} (${existing.size} tools)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
