import { NextResponse } from "next/server";
import { z } from "zod";
import { withApi, parseBody } from "@/lib/api-handler";
import { withRateLimit } from "@/lib/with-rate-limit";
import { requestCaptionRender } from "@/lib/caption-render-job";
import { serializeCaptionRenderJob } from "@/lib/captions/serialize";

const bodySchema = z
  .object({
    templateId: z.string().min(1).max(64),
    language: z.string().min(2).max(16).optional(),
    // Percent of frame. Bounded because these reach a provider's layout engine.
    position: z.object({ x: z.number().min(0).max(100), y: z.number().min(0).max(100) }).optional(),
    hook: z
      .object({
        enabled: z.boolean(),
        // Generated by Clipiro's own AI (§15) but editable by the user, so it
        // still crosses a trust boundary and is length-bounded here.
        text: z.string().min(1).max(120),
        style: z.string().max(40).optional(),
        size: z.number().min(1).max(200).optional(),
      })
      .optional(),
  })
  .strict();

/**
 * Starts a premium caption render for one clip.
 *
 * §26 is enforced structurally by this route's shape: it renders exactly ONE
 * clip, named in the path, and there is no bulk variant. Twenty AutoClip
 * candidates cannot be sent to a paid provider by accident — the user selects
 * clips and each selection is its own explicit, charged request.
 *
 * A 200 with `renderer: "native"` is a SUCCESS, not a failure: it means the
 * premium provider isn't available (flag off, tier ineligible, breaker open,
 * unconfigured) and the clip will use the template's native ASS look instead.
 * The client shows the style as applied, not an error.
 */
const handler = withApi<{ id: string; clipId: string }>(async (req, { auth, params }) => {
  const body = await parseBody(req, bodySchema);

  const result = await requestCaptionRender({
    clipId: params.clipId,
    userId: auth.userId,
    templateId: body.templateId,
    language: body.language,
    position: body.position ?? null,
    hook: body.hook ? { ...body.hook } : null,
  });

  if (!result.ok) {
    switch (result.reason) {
      case "not_found":
        return NextResponse.json({ error: "Not found" }, { status: 404 });
      case "clip_not_ready":
        return NextResponse.json(
          { error: "This clip hasn't finished rendering yet." },
          { status: 409 },
        );
      case "insufficient_credits":
        return NextResponse.json(
          { error: "insufficient_credits", required: result.required, balance: result.balance },
          { status: 402 },
        );
      case "native":
        return NextResponse.json({ renderer: "native", reason: result.fallbackReason });
    }
  }

  return NextResponse.json(
    {
      renderer: "provider",
      job: serializeCaptionRenderJob(result.job),
      duplicate: result.duplicate,
      creditsCharged: result.creditsCharged,
      ...(result.creditsRemaining != null ? { creditsRemaining: result.creditsRemaining } : {}),
    },
    { status: result.duplicate ? 200 : 201 },
  );
});

// Renders cost money, so this is rate limited per user on top of the
// idempotency key — the key stops duplicate WORK, this stops a script from
// walking a clip library and charging for all of it in one burst.
export const POST = withRateLimit(handler, {
  limit: 30,
  windowSec: 60,
  keyBy: "user",
  name: "captions:render",
});
