// The voice catalogue seed: plain data, no server imports.
//
// This is the single table the whole product's voice pickers grow from. It
// replaces SIX independently-maintained lists that had already drifted apart:
//
//   utils/voice-ids.ts VOICE_ID_MAP        (32 slugs, the only server-side truth)
//   app/components/voice-catalog.ts        (21, VoiceoverTool + VoiceChangerTool)
//   create/reddit-video/page.tsx           (24)
//   create/text-video/page.tsx             (18, plus a second list of raw ids
//                                           used to hand-build CDN preview URLs)
//   AICreatorWizard.tsx                    (19, duplicated verbatim from the above)
//   app/editor/page.tsx                    (5, RAW provider ids with no slug)
//
// Client-safe on purpose — same contract as lib/caption-templates.ts, so a
// picker can compile this in as its offline fallback when /api/voices fails.
// The server view (admin overrides + provider validation) lives in
// lib/voices/registry.ts.
//
// REBUILT 2026-09-10 FROM THE LIVE ACCOUNT. The old seed was inherited from
// those six lists, and a GET /v1/voices against the real key showed 24 of its
// 32 slugs pointed at voices ElevenLabs has retired. They do not 404 loudly —
// synthesis just fails — and one of them, `william`, was DEFAULT_VOICE_SLUG,
// so the default voice for every render was a voice that no longer exists.
//
// The 22 entries with a `previewUrl` are what the account actually has,
// verified. The rest are retired slugs kept as `aliasOf` + `active: false`:
// hidden from every picker, still resolving, because they are persisted in
// Project.voiceId rows and deleting one would break an existing project rather
// than merely change how it sounds. Which surviving voice each retired slug
// points at is a judgement call made on gender, accent and register.
//
// To re-verify: GET /v1/voices and diff against lib/voices/providerIds.ts.

/** ElevenLabs multilingual models cover these; used for the language filter. */
export const MULTILINGUAL = [
  "en", "ja", "zh", "de", "hi", "fr", "ko", "pt", "it", "es", "id", "nl", "tr",
  "fil", "pl", "sv", "bg", "ro", "ar", "cs", "el", "fi", "hr", "ms", "sk", "da",
  "ta", "uk", "ru",
];

export type VoiceGender = "male" | "female" | "neutral";
export type VoiceAge = "young" | "middle" | "mature";
/** starter = shipped with the product; library = added from the Voice Library; cloned = the user's own. */
export type VoiceCategory = "starter" | "library" | "cloned";

export interface VoiceEntry {
  slug: string;
  label: string;
  description?: string;
  /**
   * Only for voices added through the voice_catalog Config row, which have no
   * entry in the server-side id table. Seed voices leave this unset and are
   * resolved through lib/voices/providerIds.ts instead, so the ids that route a
   * paid call are not compiled into the client bundle.
   */
  providerVoiceIdOverride?: string;
  gender: VoiceGender;
  age: VoiceAge;
  accent?: string;
  /** BCP-47 codes this voice can speak. Drives the language filter. */
  languages: string[];
  category: VoiceCategory;
  /** From the provider's `free_users_allowed`. False = costs more than a credit assumes. */
  free: boolean;
  /**
   * Credit multiplier from the provider's `rate`/`fiat_rate`. Applied at SPEND
   * time, not display time — a 2x voice that charges 1x is a silent loss.
   */
  creditMultiplier: number;
  /** Provider-hosted preview mp3. Free to play; preferred over synthesizing one. */
  previewUrl?: string;
  /** Another slug that resolves to the same provider voice. Hidden in pickers. */
  aliasOf?: string;
  active?: boolean;
  sortOrder?: number;
}

export const VOICE_SEED: VoiceEntry[] = [
  {
    slug: "roger",
    label: "Roger",
    description: "Laid-Back, Casual, Resonant",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "fr", "de", "nl", "es"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/CwhRBWXzGAHq8TQ4Fs17/58ee3ff5-f6f2-4628-93b8-e38eb31806b0.mp3",
    sortOrder: 10,
  },
  {
    slug: "sarah",
    label: "Sarah",
    description: "Mature, Reassuring, Confident",
    gender: "female",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "ar", "zh", "es", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/EXAVITQu4vr4xnSDxMaL/01a3e33c-6e99-4ee7-8543-ff2216a32186.mp3",
    sortOrder: 20,
  },
  {
    slug: "laura",
    label: "Laura",
    description: "Enthusiast, Quirky Attitude",
    gender: "female",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "ar", "zh", "de"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://api.us.elevenlabs.io/v1/voices/FGY2WhTYpPnrIDTdsKH5/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJwcmVtYWRlIiwiZmlsZW5hbWUiOiI2NzM0MTc1OS1hZDA4LTQxYTUtYmU2ZS1kZTEyZmU0NDg2MTgubXAzIiwidGltZXN0YW1wIjoxNzg4OTgwNDAwMDAwMDAwfQ%3D%3D",
    sortOrder: 30,
  },
  {
    slug: "charlie",
    label: "Charlie",
    description: "Deep, Confident, Energetic",
    gender: "male",
    age: "young",
    accent: "Australian",
    languages: ["en", "zh", "pt", "fil", "es"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://api.us.elevenlabs.io/v1/voices/IKne3meq5aSn9XLyUdCD/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJwcmVtYWRlIiwiZmlsZW5hbWUiOiIxMDJkZTZmMi0yMmVkLTQzZTAtYTFmMS0xMTFmYTc1YzU0ODEubXAzIiwidGltZXN0YW1wIjoxNzg4OTgwNDAwMDAwMDAwfQ%3D%3D",
    sortOrder: 40,
  },
  {
    slug: "george",
    label: "George",
    description: "Warm, Captivating Storyteller",
    gender: "male",
    age: "middle",
    accent: "British",
    languages: ["en", "fr", "ar", "ja", "cs", "fil", "es", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://api.us.elevenlabs.io/v1/voices/JBFqnCBsd6RMkjVDRZzb/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJwcmVtYWRlIiwiZmlsZW5hbWUiOiJlNjIwNmQxYS0wNzIxLTQ3ODctYWFmYi0wNmE2ZTcwNWNhYzUubXAzIiwidGltZXN0YW1wIjoxNzg4OTgwNDAwMDAwMDAwfQ%3D%3D",
    sortOrder: 50,
  },
  {
    slug: "callum",
    label: "Callum",
    description: "Husky Trickster",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "fr", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/N2lVS1w4EtoT3dr4eOWO/ac833bd8-ffda-4938-9ebc-b0f99ca25481.mp3",
    sortOrder: 60,
  },
  {
    slug: "river",
    label: "River",
    description: "Relaxed, Neutral, Informative",
    gender: "neutral",
    age: "middle",
    accent: "American",
    languages: ["en", "it", "fr", "pt", "zh"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/SAz9YHcvj6GT2YYXdXww/e6c95f0b-2227-491a-b3d7-2249240decb7.mp3",
    sortOrder: 70,
  },
  {
    slug: "harry",
    label: "Harry",
    description: "Fierce Warrior",
    gender: "male",
    age: "young",
    accent: "American",
    languages: ["en"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/SOYHLrjzK2X1ezoPC6cr/86d178f6-f4b6-4e0e-85be-3de19f490794.mp3",
    sortOrder: 80,
  },
  {
    slug: "liam",
    label: "Liam",
    description: "Energetic, Social Media Creator",
    gender: "male",
    age: "young",
    accent: "American",
    languages: ["en", "de", "pt", "cs", "pl", "tr", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/TX3LPaxmHKxFdv7VOQHJ/63148076-6363-42db-aea8-31424308b92c.mp3",
    sortOrder: 90,
  },
  {
    slug: "alice",
    label: "Alice",
    description: "Clear, Engaging Educator",
    gender: "female",
    age: "middle",
    accent: "British",
    languages: ["en", "it", "fr", "ar", "ja", "pl", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/Xb7hH8MSUJpSbSDYk0k2/d10f7534-11f6-41fe-a012-2de1e482d336.mp3",
    sortOrder: 100,
  },
  {
    slug: "matilda",
    label: "Matilda",
    description: "Knowledgable, Professional",
    gender: "female",
    age: "middle",
    accent: "American",
    languages: ["en", "it", "fr", "de", "ar", "es"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/XrExE9yKIg1WjnnlVkGX/b930e18d-6b4d-466e-bab2-0ae97c6d8535.mp3",
    sortOrder: 110,
  },
  {
    slug: "will",
    label: "Will",
    description: "Relaxed Optimist",
    gender: "male",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "de", "pt", "zh", "cs", "fil", "sk", "es", "sv"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/bIHbv24MWmeRgasZH58o/8caf8f3d-ad29-4980-af41-53f20c72d7a4.mp3",
    sortOrder: 120,
  },
  {
    slug: "jessica",
    label: "Jessica",
    description: "Playful, Bright, Warm",
    gender: "female",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "ar", "ja", "zh", "de", "cs", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/cgSgspJ2msm6clMCkdW9/56a97bf8-b69b-448f-846c-c3a11683d45a.mp3",
    sortOrder: 130,
  },
  {
    slug: "eric",
    label: "Eric",
    description: "Smooth, Trustworthy",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "fr", "pt", "de", "sk", "es"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/cjVigY5qzO86Huf0OWal/d098fda0-6456-4030-b3d8-63aa048c9070.mp3",
    sortOrder: 140,
  },
  {
    slug: "bella",
    label: "Bella",
    description: "Professional, Bright, Warm",
    gender: "female",
    age: "middle",
    accent: "American",
    languages: ["en"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/hpp4J3VqNfWAUOO0d1Us/dab0f5ba-3aa4-48a8-9fad-f138fea1126d.mp3",
    sortOrder: 150,
  },
  {
    slug: "chris",
    label: "Chris",
    description: "Charming, Down-to-Earth",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "fr", "ar", "pt", "sv", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/iP95p4xoKVk53GoZ742B/3f4bde72-cc48-40dd-829f-57fbf906f4d7.mp3",
    sortOrder: 160,
  },
  {
    slug: "brian",
    label: "Brian",
    description: "Deep, Resonant and Comforting",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "ar", "zh", "pt", "de", "nl", "sk", "ro", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://api.us.elevenlabs.io/v1/voices/nPczCjzI2devNBz1zQrb/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJwcmVtYWRlIiwiZmlsZW5hbWUiOiIyZGQzZTcyYy00ZmQzLTQyZjEtOTNlYS1hYmM1ZDRlNWFhMWQubXAzIiwidGltZXN0YW1wIjoxNzg4OTgwNDAwMDAwMDAwfQ%3D%3D",
    sortOrder: 170,
  },
  {
    slug: "daniel",
    label: "Daniel",
    description: "Steady Broadcaster",
    gender: "male",
    age: "middle",
    accent: "British",
    languages: ["en", "de", "tr"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://api.us.elevenlabs.io/v1/voices/onwK4e9ZLuTAKqWW03F9/previews/audio?payload=eyJ2b2ljZV9zb3VyY2UiOiJwcmVtYWRlIiwiZmlsZW5hbWUiOiI3ZWVlMDIzNi0xYTcyLTRiODYtYjMwMy01ZGNhZGMwMDdiYTkubXAzIiwidGltZXN0YW1wIjoxNzg4OTgwNDAwMDAwMDAwfQ%3D%3D",
    sortOrder: 180,
  },
  {
    slug: "lily",
    label: "Lily",
    description: "Velvety Actress",
    gender: "female",
    age: "middle",
    accent: "British",
    languages: ["en", "it", "de", "zh", "cs", "nl", "pl"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/pFZP5JQG7iQjIQuC4Bku/89b68b35-b3dd-4348-a84a-a3c13a3c2b30.mp3",
    sortOrder: 190,
  },
  {
    slug: "adam",
    label: "Adam",
    description: "Dominant, Firm",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/pNInz6obpgDQGcFmaJgB/d6905d7a-dd26-4187-bfff-1bd3a5ea7cac.mp3",
    sortOrder: 200,
  },
  {
    slug: "bill",
    label: "Bill",
    description: "Wise, Mature, Balanced",
    gender: "male",
    age: "mature",
    accent: "American",
    languages: ["en", "fr", "ar", "zh", "de", "cs"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/premade/voices/pqHfZKP75CvOlQylNhV4/d782b3ff-84ba-4029-848c-acf01285524d.mp3",
    sortOrder: 210,
  },
  {
    slug: "sunny-singh",
    label: "Sunny Singh",
    description: "Dramatic, Gripping & Vivid",
    gender: "male",
    age: "young",
    languages: ["hi", "ms", "id", "el", "pl", "cs", "no", "hu", "ru", "fr", "vi", "ar", "ro", "sv", "zh", "es", "tr", "nl", "it", "ja", "pt", "en"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    previewUrl: "https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/C9mPSTSfiDpIm4wTghYI/Zo237ykp5Y4OUdwBx008.mp3",
    sortOrder: 220,
  },
  {
    slug: "rachel",
    label: "Rachel",
    description: "Retired — now speaks with Sarah's voice.",
    gender: "female",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "ar", "zh", "es", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "sarah",
    active: false,
    sortOrder: 230,
  },
  {
    slug: "natasha",
    label: "Natasha",
    description: "Retired — now speaks with Sarah's voice.",
    gender: "female",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "ar", "zh", "es", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "sarah",
    active: false,
    sortOrder: 240,
  },
  {
    slug: "freya",
    label: "Freya",
    description: "Retired — now speaks with Laura's voice.",
    gender: "female",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "ar", "zh", "de"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "laura",
    active: false,
    sortOrder: 250,
  },
  {
    slug: "aria",
    label: "Aria",
    description: "Retired — now speaks with Laura's voice.",
    gender: "female",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "ar", "zh", "de"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "laura",
    active: false,
    sortOrder: 260,
  },
  {
    slug: "elli",
    label: "Elli",
    description: "Retired — now speaks with Jessica's voice.",
    gender: "female",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "ar", "ja", "zh", "de", "cs", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "jessica",
    active: false,
    sortOrder: 270,
  },
  {
    slug: "charlotte",
    label: "Charlotte",
    description: "Retired — now speaks with Jessica's voice.",
    gender: "female",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "ar", "ja", "zh", "de", "cs", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "jessica",
    active: false,
    sortOrder: 280,
  },
  {
    slug: "spongebob",
    label: "Spongebob",
    description: "Retired — now speaks with Jessica's voice.",
    gender: "female",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "ar", "ja", "zh", "de", "cs", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "jessica",
    active: false,
    sortOrder: 290,
  },
  {
    slug: "emily",
    label: "Emily",
    description: "Retired — now speaks with Alice's voice.",
    gender: "female",
    age: "middle",
    accent: "British",
    languages: ["en", "it", "fr", "ar", "ja", "pl", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "alice",
    active: false,
    sortOrder: 300,
  },
  {
    slug: "serena",
    label: "Serena",
    description: "Retired — now speaks with Bella's voice.",
    gender: "female",
    age: "middle",
    accent: "American",
    languages: ["en"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "bella",
    active: false,
    sortOrder: 310,
  },
  {
    slug: "grace",
    label: "Grace",
    description: "Retired — now speaks with Matilda's voice.",
    gender: "female",
    age: "middle",
    accent: "American",
    languages: ["en", "it", "fr", "de", "ar", "es"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "matilda",
    active: false,
    sortOrder: 320,
  },
  {
    slug: "josh",
    label: "Josh",
    description: "Retired — now speaks with Brian's voice.",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "ar", "zh", "pt", "de", "nl", "sk", "ro", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "brian",
    active: false,
    sortOrder: 330,
  },
  {
    slug: "dandan",
    label: "Dandan",
    description: "Retired — now speaks with Brian's voice.",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "ar", "zh", "pt", "de", "nl", "sk", "ro", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "brian",
    active: false,
    sortOrder: 340,
  },
  {
    slug: "william",
    label: "William",
    description: "Retired — now speaks with Brian's voice.",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "ar", "zh", "pt", "de", "nl", "sk", "ro", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "brian",
    active: false,
    sortOrder: 350,
  },
  {
    slug: "sam",
    label: "Sam",
    description: "Retired — now speaks with Eric's voice.",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "fr", "pt", "de", "sk", "es"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "eric",
    active: false,
    sortOrder: 360,
  },
  {
    slug: "ethan",
    label: "Ethan",
    description: "Retired — now speaks with Chris's voice.",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "fr", "ar", "pt", "sv", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "chris",
    active: false,
    sortOrder: 370,
  },
  {
    slug: "dave",
    label: "Dave",
    description: "Retired — now speaks with Will's voice.",
    gender: "male",
    age: "young",
    accent: "American",
    languages: ["en", "fr", "de", "pt", "zh", "cs", "fil", "sk", "es", "sv"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "will",
    active: false,
    sortOrder: 380,
  },
  {
    slug: "matthew",
    label: "Matthew",
    description: "Retired — now speaks with George's voice.",
    gender: "male",
    age: "middle",
    accent: "British",
    languages: ["en", "fr", "ar", "ja", "cs", "fil", "es", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "george",
    active: false,
    sortOrder: 390,
  },
  {
    slug: "amir1",
    label: "Amir1",
    description: "Retired — now speaks with George's voice.",
    gender: "male",
    age: "middle",
    accent: "British",
    languages: ["en", "fr", "ar", "ja", "cs", "fil", "es", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "george",
    active: false,
    sortOrder: 400,
  },
  {
    slug: "amir2",
    label: "Amir2",
    description: "Retired — now speaks with Liam's voice.",
    gender: "male",
    age: "young",
    accent: "American",
    languages: ["en", "de", "pt", "cs", "pl", "tr", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "liam",
    active: false,
    sortOrder: 410,
  },
  {
    slug: "clyde",
    label: "Clyde",
    description: "Retired — now speaks with Callum's voice.",
    gender: "male",
    age: "middle",
    accent: "American",
    languages: ["en", "fr", "hi"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "callum",
    active: false,
    sortOrder: 420,
  },
  {
    slug: "patrick",
    label: "Patrick",
    description: "Retired — now speaks with Harry's voice.",
    gender: "male",
    age: "young",
    accent: "American",
    languages: ["en"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "harry",
    active: false,
    sortOrder: 430,
  },
  {
    slug: "fin",
    label: "Fin",
    description: "Retired — now speaks with Bill's voice.",
    gender: "male",
    age: "mature",
    accent: "American",
    languages: ["en", "fr", "ar", "zh", "de", "cs"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "bill",
    active: false,
    sortOrder: 440,
  },
  {
    slug: "thomas",
    label: "Thomas",
    description: "Retired — now speaks with River's voice.",
    gender: "neutral",
    age: "middle",
    accent: "American",
    languages: ["en", "it", "fr", "pt", "zh"],
    category: "starter",
    free: true,
    creditMultiplier: 1,
    aliasOf: "river",
    active: false,
    sortOrder: 450,
  },
];

/** Slug → entry. Built once; the picker and the resolver both read it. */
export const VOICE_BY_SLUG: Record<string, VoiceEntry> = Object.fromEntries(
  VOICE_SEED.map((v) => [v.slug, v]),
);

/** The default when nothing is chosen. Every old list defaulted to this one. */
export const DEFAULT_VOICE_SLUG = "brian";
